### ISSUE TITLE
When trying to start new discussion for a new file/folder I get a 403 error message

### ISSUE THREAD

**Issue by lucianpricop** [newroco/rocket_integration#2]
403 message is visible only in Network tab of the developer tools. It's for URL
https://<NC URL>/apps/rocket_integration/file

The message is 
{"message":"Could not create channel. ({\"status\":\"fail\",\"message\":{\"status\":\"error\",\"message\":\"You must be logged in to do this.\"}})"}

I am logged in on both NC and rocket with same username using same CAS provider for both.

**Comment by orzuionut** [comment]
This is due to the fact that the Rocket credentials entered in the NC admin settings were wrong.
